### ISSUE TITLE
s3boto backend has been removed in django-storages in favor of s3boto3

### ISSUE THREAD

**Issue by fredd4** [divio/aldryn-django#208] opened 2020-02-04 11:22 UTC
https://github.com/jschneier/django-storages/commit/abcb31149e2fa24e5d8e4843ff93ba8ca80ea338

**Comment by matthiasrohmer** [comment] 2020-02-04 19:01
For anyone who has trouble building their containers in the meantime: fixing django-storages to 1.7.2 in your requirements.in fixes it. At least temporarily.

**Comment by jonathan-s** [comment] 2020-02-12 12:15
thanks @matthiasrohmer !

**Comment by Aiky30** [comment] 2020-02-12 12:31
Duplicate of: https://github.com/divio/aldryn-django/issues/154

**Comment by FinalAngel** [comment] 2020-08-31 11:47
We are working towards a solution in #209 

closing as it is a duplicate of #154 as earlier mentioned

**Closed as completed by FinalAngel** 2020-08-31 11:47 UTC
